---
- hosts: all

  tasks:
    - name: Download CloudbaseInit setup file
      ansible.windows.win_get_url:
        url: https://cloudbase.it/downloads/CloudbaseInitSetup_1_1_2_x64.msi
        dest: C:\CloudbaseInitSetup_1_1_2_x64.msi

    - name: Install CloudbaseInit
      ansible.windows.win_package:
        path: C:\CloudbaseInitSetup_1_1_2_x64.msi
        arguments:
          - /qn

    - name: Remove CloudbaseInit setup file
      ansible.windows.win_file:
        path: C:\CloudbaseInitSetup_1_1_2_x64.msi
        state: absent

    - name: Install windows updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: yes
        reboot_timeout: 10000
      register: windows_updates
      until: windows_updates.installed_update_count == 0
