---
- hosts: all
  tasks:
    # Workaround for windows 2025 images to remove WinRE partition which has to be present during installation
    - name: Get disk physical_disk and partition facts on the target
      community.windows.win_disk_facts:
        filter:
          - partitions

    - name: Print partition table
      ansible.builtin.debug:
        var: ansible_facts.disks[0].partitions

    - name: Disable WinRE for 2025 servers
      ansible.windows.win_command:
        cmd: reagentc /disable
      when: '"2025" in ansible_distribution' 

    - name: Remove WinRE partition if it exists (always last)
      community.windows.win_partition:
        disk_number: 0
        partition_number: ansible_facts.disks[0].partitions | length
        state: absent
      when: '"2025" in ansible_distribution' 

    - name: Download CloudbaseInit setup file
      ansible.windows.win_get_url:
        url: https://cloudbase.it/downloads/CloudbaseInitSetup_1_1_6_x64.msi
        dest: C:\CloudbaseInitSetup_1_1_6_x64.msi

    - name: Install CloudbaseInit
      ansible.windows.win_package:
        path: C:\CloudbaseInitSetup_1_1_6_x64.msi
        arguments:
          - /qn

    - name: Wait 300 seconds, but only start checking after 60 seconds
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 300

    - name: Remove CloudbaseInit setup file
      ansible.windows.win_file:
        path: C:\CloudbaseInitSetup_1_1_6_x64.msi
        state: absent

    - name: Install windows updates
      ansible.windows.win_updates:
        category_names: '*'
        reject_list:
          - KB5034439  # This update requires a recovery partition which we don't have (https://support.microsoft.com/en-us/topic/kb5034439-windows-recovery-environment-update-for-windows-server-2022-january-9-2024-6f9d26e6-784c-4503-a3c6-0beedda443ca)
          - KB5060842  # This update can cause bsod in certain conditions
        reboot: yes
        reboot_timeout: 600
      register: windows_updates
      until: windows_updates.installed_update_count == 0
      retries: 10
